import type { ScenarioDefinition } from './types';
import { initiative, metric, synergy } from './scenarioHelpers';

export const care360: ScenarioDefinition = {
  id: 'care360', name: 'Care360 Health Network', industry: 'Healthcare', icon: '🏥', description: 'Improve access and patient outcomes across a growing healthcare network without compromising trust.', difficulty: 'advanced',
  company: { name: 'Care360', revenue: '₹1,200 Cr', employees: '4,000 clinicians', locations: '12 hospitals · 35 centres', description: 'A healthcare provider balancing patient flow, clinician capacity, safety, and privacy.' },
  challenges: [
    { id: 'wait', label: 'Patient wait times', severity: '75 minutes', metric: 'patientWaitTime', direction: 'lower-is-better', description: 'Long queues are damaging access and patient experience.' },
    { id: 'burnout', label: 'Clinician burnout', severity: '58 index', metric: 'clinicianBurnout', direction: 'lower-is-better', description: 'Overworked clinical and administrative teams need relief.' },
    { id: 'trust', label: 'Privacy and trust', severity: '65 index', metric: 'privacyTrust', direction: 'higher-is-better', description: 'AI must improve care while protecting patient trust.' },
  ],
  startingState: { budget: 5, defaultAllocation: { infra: 20, data: 25, people: 20, mlops: 10, compliance: 20, innovation: 5 }, startingMetrics: { patientWaitTime: 75, clinicianBurnout: 58, patientSafety: 70, privacyTrust: 65, careAccess: 50, efficiency: 30, adoption: 42, data: 55, satisfaction: 52 } },
  progress: [metric('patientWaitTime', 'Patient wait time', 'minutes', 75, 30, 'lower-is-better', 0, 240), metric('clinicianBurnout', 'Clinician burnout', 'index', 58, 30, 'lower-is-better'), metric('patientSafety', 'Patient safety', 'index', 70, 90, 'higher-is-better'), metric('privacyTrust', 'Privacy trust', 'index', 65, 90, 'higher-is-better'), metric('careAccess', 'Care access', '%', 50, 85, 'higher-is-better')],
  initiatives: [
    initiative({ id: 'radiologyAssistant', name: 'AI Radiology Assistant', desc: 'Support imaging review so clinicians can focus on critical cases.', cost: 1.6, roi: 160, risk: 'HIGH', data: 5, human: 4, impact: 'Improves diagnostic throughput.', baseEffect: -10, primaryMetric: 'patientWaitTime', effectUnit: 'minutes', frameworkContribution: { peopleChange: 85, processWorkflow: 70, techData: 90, algorithmModel: 95 }, lifecycleProfile: { dataReadiness: 86, evaluation: { criteria: [{ id: 'report-turnaround', label: 'Reduce report turnaround time', metric: 'patientWaitTime', threshold: -6, direction: 'lower-is-better', kind: 'outcome' }, { id: 'clinician-safety', label: 'Keep clinician override and review coverage', metric: 'clinicalReviewCoverage', threshold: 95, direction: 'higher-is-better', kind: 'safety', required: true }], goThreshold: 1, conditionalThreshold: .5 }, deployment: { defaultMode: 'augmentation', modes: { augmentation: { efficiencyDelta: 8, riskDelta: -8, trustDelta: 5, oversightUnits: 3 }, automation: { efficiencyDelta: 18, riskDelta: 20, trustDelta: -12, oversightUnits: 5 } } }, risks: { model: 58, operational: 66, legal: 78 }, drift: { susceptibility: 30, quarterlyRate: 2, degradationThreshold: 65, monitoringRequired: true }, oversight: { baseUnits: 3, automationUnits: 5 }, autonomy: 'advisory', autonomyBoundaries: 'The assistant prioritises and annotates images; a qualified clinician signs every report and can override the model.', flywheel: { active: true, quality: 88, recipientIds: ['riskScoring', 'schedulingOptimization'] } } }),
    initiative({ id: 'docCopilot', name: 'Clinical Documentation Copilot', desc: 'Reduce documentation burden at the point of care.', cost: 1.3, roi: 150, risk: 'MED', data: 4, human: 4, impact: 'Reduces clinician burden.', baseEffect: -5, primaryMetric: 'clinicianBurnout', effectUnit: 'index points', frameworkContribution: { peopleChange: 90, processWorkflow: 85, techData: 75, algorithmModel: 80 } }),
    initiative({ id: 'riskScoring', name: 'Predictive Patient Risk Scoring', desc: 'Identify high-risk profiles early for proactive intervention.', cost: 1.7, roi: 170, risk: 'HIGH', data: 5, human: 4, impact: 'Improves patient safety.', baseEffect: 4, primaryMetric: 'patientSafety', effectUnit: 'index points', frameworkContribution: { peopleChange: 85, processWorkflow: 70, techData: 90, algorithmModel: 95 }, lifecycleProfile: { dataReadiness: 82, evaluation: { criteria: [{ id: 'safety-signal', label: 'Improve early safety signal recall', metric: 'patientSafety', threshold: 3, direction: 'higher-is-better', kind: 'outcome' }, { id: 'equity-review', label: 'Pass cohort-level equity review', metric: 'equityReviewScore', threshold: 85, direction: 'higher-is-better', kind: 'safety', required: true }], goThreshold: 1, conditionalThreshold: .5 }, deployment: { defaultMode: 'augmentation', modes: { augmentation: { efficiencyDelta: 5, riskDelta: -9, trustDelta: 6, oversightUnits: 3 }, automation: { efficiencyDelta: 12, riskDelta: 22, trustDelta: -14, oversightUnits: 5 } } }, risks: { model: 64, operational: 62, legal: 84 }, drift: { susceptibility: 34, quarterlyRate: 2, degradationThreshold: 70, monitoringRequired: true }, oversight: { baseUnits: 3, automationUnits: 5 }, autonomy: 'advisory', autonomyBoundaries: 'Risk scores inform care-team outreach only; clinicians decide interventions and patients retain appeal routes.' } }),
    initiative({ id: 'schedulingOptimization', name: 'Appointment Scheduling Optimization', desc: 'Coordinate queues and visits across the network.', cost: 1.2, roi: 155, risk: 'LOW', data: 4, human: 3, impact: 'Reduces waiting.', baseEffect: -15, primaryMetric: 'patientWaitTime', effectUnit: 'minutes', frameworkContribution: { peopleChange: 75, processWorkflow: 95, techData: 80, algorithmModel: 75 } }),
    initiative({ id: 'patientVirtualAssistant', name: 'Patient Virtual Assistant', desc: 'Provide reliable digital guidance and access around the clock.', cost: 1.1, roi: 140, risk: 'MED', data: 3, human: 3, impact: 'Expands care access.', baseEffect: 6, primaryMetric: 'careAccess', effectUnit: 'percentage points', frameworkContribution: { peopleChange: 80, processWorkflow: 80, techData: 75, algorithmModel: 75 } }),
    initiative({ id: 'workforcePlanning', name: 'Workforce Planning AI', desc: 'Forecast demand and deploy clinical teams more effectively.', cost: 1.4, roi: 145, risk: 'MED', data: 4, human: 4, impact: 'Reduces workload pressure.', baseEffect: -4, primaryMetric: 'clinicianBurnout', effectUnit: 'index points', frameworkContribution: { peopleChange: 85, processWorkflow: 90, techData: 85, algorithmModel: 80 } }),
  ],
  synergies: [
    synergy({ key: 'radiologyAssistant:schedulingOptimization', initiativeIds: ['radiologyAssistant', 'schedulingOptimization'], label: 'Faster safe access', description: 'More efficient imaging capacity is valuable when appointment flow is coordinated around it.', roiBoost: 0.06, riskReduction: 2, adoptionBoost: 2, costReduction: 0.02 }),
    synergy({ key: 'docCopilot:workforcePlanning', initiativeIds: ['docCopilot', 'workforcePlanning'], label: 'Clinician capacity loop', description: 'Less documentation burden and better staffing forecasts reinforce clinician resilience.', roiBoost: 0.05, riskReduction: 2, adoptionBoost: 2, costReduction: 0.02 }),
    synergy({ key: 'riskScoring:patientVirtualAssistant', initiativeIds: ['riskScoring', 'patientVirtualAssistant'], label: 'Proactive care bridge', description: 'Early risk signals become more useful when patients can be guided toward timely support.', roiBoost: 0.04, riskReduction: 3, adoptionBoost: 3, costReduction: 0.01 }),
  ],
  crises: [
    { title: 'A privacy concern pauses an AI pilot.', type: 'PRIVACY REVIEW', text: 'Clinical leaders want progress, but patients and regulators need evidence of control.', options: [{ label: 'Pause and review', description: 'Strengthen controls before scaling.', cost: 0.5, impacts: { risk: -8, compliance: 6, privacyTrust: 5 } }, { label: 'Continue with guardrails', description: 'Preserve momentum with a narrower rollout.', cost: 0.3, impacts: { adoption: 4, risk: 3, privacyTrust: 1 } }, { label: 'Return to clinician-only review', description: 'Protect patient confidence while the evidence base is rebuilt.', impacts: { adoption: -3, risk: -5, patientSafety: 2, privacyTrust: 4 } }] },
    { title: 'A seasonal surge creates unsafe waiting-room queues.', type: 'ACCESS SURGE', text: 'Demand is exceeding capacity across several centres. Leaders need relief without shifting pressure onto clinicians.', options: [{ label: 'Rebalance appointments', description: 'Use scheduling intelligence to move capacity toward the highest-pressure centres.', cost: 0.5, impacts: { efficiency: 6, patientWaitTime: -12, adoption: 3 } }, { label: 'Add temporary clinical capacity', description: 'Bring in short-term support while the network absorbs the surge.', cost: 0.8, impacts: { satisfaction: 5, patientWaitTime: -8, clinicianBurnout: 3 } }, { label: 'Protect only critical cases', description: 'Prioritise urgent care and accept slower routine access.', impacts: { risk: 4, patientWaitTime: 10, careAccess: -4 } }] },
    { title: 'A model flags an unexpected patient safety pattern.', type: 'CLINICAL SAFETY SIGNAL', text: 'The signal may indicate a real deterioration in outcomes, but the clinical team needs a safe way to validate it.', options: [{ label: 'Clinical validation sprint', description: 'Pair the model team with clinicians to investigate the signal.', cost: 0.6, impacts: { risk: -7, patientSafety: 6, compliance: 4 } }, { label: 'Targeted intervention', description: 'Act on the signal for a defined cohort with human oversight.', cost: 0.4, impacts: { patientSafety: 8, adoption: 2, risk: 2 } }, { label: 'Suppress the alert temporarily', description: 'Avoid disruption while the signal is investigated.', impacts: { patientSafety: -5, risk: 8, adoption: -2 } }] },
  ],
  currency: { defaultSymbol: '₹', defaultLabel: 'Cr' }, frameworkContext: { advisorPrompt: 'Connect decisions to patient access, clinician workload, safety, privacy, and trust. Healthcare AI requires human oversight and careful evidence before scale.', industryBenchmarks: { patientSafety: 90, privacyTrust: 90, careAccess: 85 } },
};
