'use client';
import { Activity, BrainCircuit, GitBranch, LineChart, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import CampaignTools from './CampaignTools';
import FrameworkDashboard from './FrameworkDashboard';
import HistoricalComparison from './HistoricalComparison';
import InitiativeEvolution from './InitiativeEvolution';
import LLMSettings from './LLMSettings';
import MagicAnalytics from './MagicAnalytics';
import StrategySimulator from './StrategySimulator';
import TransformationKPIDashboard from './TransformationKPIDashboard';
import QuarterRoadmap from './QuarterRoadmap';
import { calculateTransformationKPIs } from '../lib/analytics';
import { getScenario } from '../lib/scenarios/registry';
import { formatBudget, formatCurrency } from '../lib/currency';

export default function AnalyticsHub({ state, initiatives }: { state: any; initiatives: any[] }) {
  const [open, setOpen] = useState(false); const [tab, setTab] = useState('dashboard'); const [sandbox, setSandbox] = useState(false);
  const history = useMemo(() => state.history || [], [state.history]); const previous = history.length > 1 ? history[history.length - 2].metrics : null;
  const tabs = [['dashboard','Dashboard',Activity],['kpis','KPIs',Target],['trends','Trends',LineChart],['diagnostics','Diagnostics',ShieldCheck],['frameworks','Frameworks',BrainCircuit],['history','History',GitBranch],['evolution','DNA',Sparkles],['learn','Learn',Sparkles]] as const;
  const metrics = [['Risk exposure', state.risk, 20, 'risk'], ['Efficiency', state.efficiency, 55, 'efficiency'], ['AI literacy', state.literacy, 70, 'literacy'], ['Satisfaction', state.satisfaction, 75, 'satisfaction']] as const;
  const scenario = state.scenarioMode ? getScenario(state.scenarioId) : undefined;
  const scenarioMetrics = state.scenarioState?.metrics || {};
  const scenarioMetricValue = (item: { key: string; unit: string }) => {
    const value = Number(scenarioMetrics[item.key] ?? scenario?.startingState.startingMetrics[item.key] ?? 0);
    return `${value.toFixed(item.unit === '%' ? 0 : 1)}${item.unit === '%' ? '%' : ` ${item.unit}`}`;
  };
  return <><button aria-label="Open analytics" onClick={() => setOpen(true)} className="fixed bottom-3 left-1/2 z-30 flex -translate-x-1/2 items-center gap-2 whitespace-nowrap rounded-xl border border-emerald bg-ink px-4 py-3 text-xs font-bold text-white shadow-xl sm:bottom-5 sm:left-auto sm:right-5 sm:translate-x-0"><Activity size={16} className="text-emerald"/> Analytics <span className="rounded bg-emerald px-2 py-0.5 text-ink">Q{state.q}/12</span></button>{open && <div className="fixed inset-0 z-40 bg-ink/35" onClick={() => setOpen(false)}><aside role="dialog" aria-label="Insights and analytics" onClick={event => event.stopPropagation()} className="absolute right-0 top-0 flex h-full w-full max-w-[720px] flex-col bg-ink text-white shadow-2xl"><header className="flex items-center justify-between border-b border-white/10 p-4 sm:p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald">Always-on intelligence</p><h2 className="mt-1 text-xl font-bold">Insights & analytics</h2></div><button onClick={() => setOpen(false)} aria-label="Close analytics"><X size={18}/></button></header><nav className="grid grid-cols-8 border-b border-white/10 bg-white/[.03]">{tabs.map(([id,label,Icon]) => <button key={id} title={label} onClick={() => setTab(id)} className={`flex items-center justify-center gap-1 border-b-2 px-1 py-3 text-[10px] font-bold uppercase tracking-wider ${tab === id ? 'border-emerald bg-emerald/10 text-emerald' : 'border-transparent text-white/45'}`}><Icon size={14}/><span className="hidden sm:inline">{label}</span></button>)}</nav><div className="flex-1 overflow-y-auto p-4 sm:p-5">
  {tab === 'dashboard' && <div className="space-y-5"><LLMSettings/><div className="grid grid-cols-2 gap-3">{[['ROI',state.roi,35],['Adoption',state.adoption,67],['Data readiness',state.data,80],['Employee trust',state.satisfaction,75]].map(([label,value,benchmark]) => <div key={label as string} className="rounded-xl border border-white/10 bg-white/5 p-4"><p className="text-[10px] uppercase text-white/45">{label as string}</p><p className="mt-2 text-2xl font-bold text-emerald">{Number(value).toFixed(label === 'ROI' ? 1 : 0)}%</p><p className="mt-2 text-[10px] text-white/40">Benchmark {benchmark}%</p></div>)}</div>{scenario && <section className="rounded-xl border border-sky-400/30 bg-sky-400/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-sky-200">Live scenario state</p><b className="mt-1 block">{scenario.name}</b></div><span className="text-right text-xs font-bold text-sky-100">{formatBudget(state.scenarioBudgetRemaining ?? state.quarterlyBudget, state.currencyMode)} remaining</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{scenario.progress.map((item) => <div key={item.key} className="rounded-lg bg-ink/35 p-3"><div className="flex justify-between gap-2 text-xs"><span className="text-white/70">{item.label}</span><b className="text-sky-100">{scenarioMetricValue(item)}</b></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-sky-300" style={{ width: `${Math.min(100, Math.max(0, Number(state.scenarioState?.progress?.[item.key] || 0)))}%` }} /></div></div>)}</div><p className="mt-3 text-[10px] text-white/50">These are the domain metrics driving your current scenario—not generic portfolio proxies.</p></section>}<div className="rounded-xl border border-white/10 bg-white/5 p-4"><b>Portfolio spend</b><p className="mt-2 text-3xl font-bold text-gold">{formatCurrency(Number(state.spent), state.currencyMode)}</p><p className="text-xs text-white/45">Total campaign investment across all initiatives</p></div><button onClick={() => setSandbox(true)} className="w-full rounded-xl bg-emerald px-4 py-3 text-sm font-bold text-ink">Open Strategy Simulator</button></div>}
  {tab === 'kpis' && <TransformationKPIDashboard state={state} kpis={calculateTransformationKPIs(state, initiatives)}/>} 
  {tab === 'trends' && <MagicAnalytics state={state}/>} 
  {tab === 'diagnostics' && <div className="space-y-5"><div className="rounded-xl border border-rose-400/30 bg-rose-400/10 p-5"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-rose-200"/><b>Failure diagnosis</b></div><p className="mt-3 text-sm text-white/65">Diagnostics explains why performance is weak and what capability should change next.</p><div className="mt-4 space-y-3">{[['Risk / reward', `${Number(state.roi / Math.max(state.risk, 1)).toFixed(1)}x`, 'Is value compensating for exposure?'],['Weakest capability', state.data < state.adoption ? 'Data readiness' : state.risk > 35 ? 'Governance' : 'Adoption', 'The first area to strengthen'],['Historical evidence', `${history.length} completed quarters`, 'Use History to compare the turning points']].map(([label,value,detail]) => <div key={label} className="rounded-lg bg-black/15 p-3"><p className="text-xs text-white/45">{label}</p><b className="block text-lg text-rose-100">{value}</b><span className="text-[10px] text-white/50">{detail}</span></div>)}</div></div><div className="rounded-xl border border-white/10 bg-white/5 p-5"><b>Metric movement versus last quarter</b><div className="mt-4 space-y-3">{metrics.map(([label,value,,key]) => { const delta = previous ? Number(value) - Number(previous[key]) : 0; return <p key={label} className="flex justify-between text-sm"><span className="text-white/60">{label}</span><b className={delta >= 0 ? 'text-emerald' : 'text-rose-200'}>{delta >= 0 ? '+' : ''}{delta.toFixed(1)}%</b></p>; })}</div></div></div>}
  {tab === 'frameworks' && <FrameworkDashboard state={state} initiatives={initiatives}/>} {tab === 'history' && <div className="space-y-4"><QuarterRoadmap state={state}/><HistoricalComparison state={state}/></div>} {tab === 'evolution' && <InitiativeEvolution state={state} initiatives={initiatives}/>} {tab === 'learn' && <div className="space-y-5"><LLMSettings/><div className="rounded-xl border border-white/10 bg-white/5 p-5"><Sparkles className="text-emerald"/><h3 className="mt-3 text-xl font-bold">Learning loop</h3><p className="mt-2 text-sm leading-6 text-white/60">Compare each decision with its outcome. Use approved recommendations and initiative spend to make the next quarter more deliberate.</p><p className="mt-4 text-3xl font-bold">Q{state.q}<span className="text-sm font-normal text-white/45"> / 12</span></p></div></div>}
  <CampaignTools state={state}/></div></aside></div>}{sandbox && <StrategySimulator state={state} initiatives={initiatives} onClose={() => setSandbox(false)}/>}</>;
}
