import { ArrowRight, Factory } from 'lucide-react';

interface GameSetupScreenProps {
  name: string;
  experimental: boolean;
  onNameChange: (name: string) => void;
  onExperimentalChange: (experimental: boolean) => void;
  onContinue: () => void;
}

export default function GameSetupScreen({ name, experimental, onNameChange, onExperimentalChange, onContinue }: GameSetupScreenProps) {
  return <main className="min-h-screen grid-bg"><header className="mx-auto flex max-w-7xl items-center gap-3 px-6 py-7"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-ink font-bold text-gold">AI</div><b className="text-sm tracking-[.18em]">THE AI INVESTMENT CHALLENGE</b></header><section className="mx-auto max-w-5xl px-6 pb-20 pt-12"><p className="text-xs font-bold uppercase tracking-[.25em] text-gold">Scenario briefing · 01</p><h1 className="mt-5 max-w-3xl text-6xl font-semibold tracking-[-.06em]">Welcome to <span className="serif italic text-gold">Project Factory 2030.</span></h1><div className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-[2rem] bg-ink p-8 text-white"><div className="flex items-center gap-3 text-gold"><Factory size={22}/><span className="text-xs font-bold uppercase tracking-widest">Automotive manufacturing</span></div><p className="mt-6 text-2xl leading-relaxed">You are the incoming Chief AI Officer at a ₹2,500 Cr component manufacturer.</p><p className="mt-4 leading-7 text-white/60">Five plants. 7,000 employees. 24×7 production. Your mandate is simple: create durable value without losing the people or the trust that make the business work.</p><div className="mt-8 grid grid-cols-3 gap-3">{[['5','plants'],['7,000','employees'],['12','quarters']].map(x=><div key={x[1]} className="rounded-xl bg-white/8 p-4"><b className="text-xl">{x[0]}</b><p className="mt-1 text-xs text-white/45">{x[1]}</p></div>)}</div></div><div className="rounded-[2rem] border border-ink/10 bg-white p-8"><p className="text-xs font-bold uppercase tracking-widest text-ink/45">Your profile</p><label className="mt-7 block text-sm font-bold">Name <span className="font-normal text-ink/40">(optional)</span></label><input value={name} onChange={e=>onNameChange(e.target.value)} placeholder="e.g. Priya Sharma" className="mt-2 w-full rounded-xl border border-ink/10 bg-mist px-4 py-3 outline-none focus:border-gold"/><label className="mt-5 flex items-center gap-3 rounded-xl bg-mist p-3 text-sm"><input type="checkbox" checked={experimental} onChange={e=>onExperimentalChange(e.target.checked)} className="accent-[#D4AF37]"/><span><b>Experimental mode</b><small className="block text-ink/50">Practice hypotheses with softened consequences.</small></span></label><p className="mt-5 text-sm leading-6 text-ink/55">Before the boardroom, answer five quick questions. Your baseline helps the final report show how your thinking evolved.</p><button onClick={onContinue} className="mt-7 flex w-full items-center justify-center gap-3 rounded-xl bg-ink px-5 py-4 text-sm font-bold text-white">Take the baseline assessment <ArrowRight size={16}/></button></div></div></section></main>;
}
