'use client';
import { ArrowRight, BarChart3, CheckCircle2, ClipboardList, GitBranch, RefreshCw, Target } from 'lucide-react';
import { useState } from 'react';

const steps = [
  { label: 'Brief', title: 'Start with context', copy: 'Review Project Factory 2030, choose an LLM advisor, and complete the baseline.', action: 'Start your transformation, answer the baseline questions, then enter the boardroom.', Icon: ClipboardList },
  { label: 'Decide', title: 'Balance the operating system', copy: 'Choose up to three initiatives and allocate the budget across six operating categories.', action: 'Keep the allocation at 100% and submit the quarter.', Icon: Target },
  { label: 'Simulate', title: 'Test before committing', copy: 'Use What-If analysis to compare projected ROI, adoption, risk, and risk-adjusted return.', action: 'Open Strategy Simulator, try a preset or custom portfolio, then apply it.', Icon: GitBranch },
  { label: 'Results', title: 'See what your choice caused', copy: 'Read live metrics, causal chain, top recommendations, crisis events, and BCG influence.', action: 'Approve useful recommendations, respond to crises, and continue.', Icon: CheckCircle2 },
  { label: 'Analyse', title: 'Turn each quarter into learning', copy: 'Use KPIs, Strategy DNA, forecasts, heatmaps, failure analysis, frameworks, history, and Time Machine.', action: 'Open Analytics after each result and switch tabs.', Icon: BarChart3 },
  { label: 'Repeat', title: 'Build strategic judgement', copy: 'Advance through Q1–Q12. Your campaign persists through refreshes and can be safely reset.', action: 'Continue the loop, review your verdict, or reset and test again.', Icon: RefreshCw },
];

export default function HowToPlayGuide() {
  const [active, setActive] = useState(0); const step = steps[active]; const Icon = step.Icon;
  return <section id="how-to-play" className="scroll-mt-24 border-y border-[#d0d7de] bg-[#f6f8fa]"><div className="mx-auto max-w-7xl px-6 py-24"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#08872b]">How to play</p><h2 className="mt-4 text-4xl font-bold tracking-[-.04em] md:text-6xl">Follow the decision loop.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[#656d76]">Use this walkthrough while you play: understand, choose, test, learn, and improve.</p><div className="mt-12 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><nav className="grid gap-2" aria-label="How to play steps">{steps.map((item, index) => <button key={item.label} onClick={() => setActive(index)} className={`flex items-center gap-3 rounded-xl border p-4 text-left ${active === index ? 'border-[#08872b] bg-white shadow-sm' : 'border-transparent bg-white/60'}`}><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${active === index ? 'bg-[#08872b] text-white' : 'bg-[#08872b]/10 text-[#08872b]'}`}><item.Icon size={17}/></span><span><b className="block text-sm">{index + 1}. {item.label}</b><small className="text-[#656d76]">{item.title}</small></span></button>)}</nav><article className="rounded-2xl bg-[#0d1117] p-7 text-white shadow-xl"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-[.2em] text-[#3fb950]">Step {active + 1} of {steps.length}</span><Icon className="text-[#3fb950]" size={24}/></div><h3 className="mt-8 text-3xl font-bold">{step.title}</h3><p className="mt-4 max-w-xl leading-7 text-white/65">{step.copy}</p><div className="mt-8 rounded-xl border border-[#3fb950]/30 bg-[#3fb950]/10 p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#3fb950]">What to do</p><p className="mt-2 text-sm leading-6 text-white/80">{step.action}</p></div><div className="mt-8 flex justify-between"><button disabled={!active} onClick={() => setActive(active - 1)} className="rounded-lg border border-white/15 px-4 py-2 text-sm font-bold text-white/70 disabled:opacity-30">← Previous</button><button onClick={() => setActive(active === steps.length - 1 ? 0 : active + 1)} className="flex items-center gap-2 rounded-lg bg-[#3fb950] px-4 py-2 text-sm font-bold text-[#0d1117]">{active === steps.length - 1 ? 'Start again' : 'Next step'} <ArrowRight size={15}/></button></div></article></div></div></section>;
}
