'use client';

import { useMemo } from 'react';
import { Activity, TrendingDown, TrendingUp } from 'lucide-react';

export default function InitiativeEvolution({ state, initiatives }: { state: any; initiatives: any[] }) {
  const snapshots = useMemo(() => state.history || [], [state.history]);
  const rows = useMemo(() => initiatives.map(init => {
    const points = snapshots.map((snapshot: any) => snapshot.initiativeStates?.[init.id]).filter(Boolean);
    const current = state.initiativeStates?.[init.id] || init;
    return { init, current, first: points[0] || current, points };
  }), [initiatives, snapshots, state.initiativeStates]);
  return <div className="space-y-4"><div className="rounded-xl border border-sky-400/30 bg-sky-400/10 p-4"><div className="flex items-center gap-2"><Activity size={17} className="text-sky-200"/><b>Initiative evolution</b><span className="ml-auto text-[10px] text-white/45">{snapshots.length} quarter snapshots</span></div><p className="mt-1 text-xs leading-5 text-white/55">See how funding, learning, and neglect change each initiative over time.</p></div><div className="space-y-3">{rows.map(({ init, current, first, points }) => { const dataDelta = Number(current.currentData ?? current.data) - Number(first.currentData ?? first.data); const roiDelta = Number(current.currentRoi ?? current.roi) - Number(first.currentRoi ?? first.roi); return <article key={init.id} className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-start justify-between gap-3"><div><h4 className="font-bold">{init.name}</h4><p className="mt-1 text-[10px] text-white/45">{current.maturityLevel || 'nascent'} · funded {current.quartersFunded || 0} quarters</p></div><span className="rounded-full bg-emerald/10 px-2 py-1 text-[10px] font-bold text-emerald">${Number(current.currentCost ?? current.cost).toFixed(2)}M</span></div><div className="mt-4 grid grid-cols-2 gap-3"><div><div className="flex justify-between text-[10px] text-white/55"><span>Data readiness</span><span>{Number(current.currentData ?? current.data).toFixed(1)}/5</span></div><div className="mt-1 h-2 rounded bg-white/10"><div className="h-full rounded bg-sky-300" style={{width:`${Math.min(100, Number(current.currentData ?? current.data) / 5 * 100)}%`}}/></div><p className={`mt-1 flex items-center gap-1 text-[10px] ${dataDelta >= 0 ? 'text-emerald' : 'text-crimson'}`}>{dataDelta >= 0 ? <TrendingUp size={11}/> : <TrendingDown size={11}/>} {dataDelta >= 0 ? '+' : ''}{dataDelta.toFixed(1)} since start</p></div><div><div className="flex justify-between text-[10px] text-white/55"><span>Current ROI</span><span>{Number(current.currentRoi ?? current.roi).toFixed(0)}%</span></div><div className="mt-1 h-2 rounded bg-white/10"><div className="h-full rounded bg-emerald" style={{width:`${Math.min(100, Number(current.currentRoi ?? current.roi) / 2)}%`}}/></div><p className={`mt-1 text-[10px] ${roiDelta >= 0 ? 'text-emerald' : 'text-crimson'}`}>{roiDelta >= 0 ? '+' : ''}{roiDelta.toFixed(0)} pts since start · risk {current.currentRisk ?? current.risk}</p></div></div><p className="mt-3 text-[10px] text-white/40">{points.length ? `Last recorded at Q${snapshots[snapshots.length - 1]?.q}` : 'No completed-quarter snapshot yet; showing baseline.'}</p></article>; })}</div></div>;
}
