'use client';
import { useMemo, useState } from 'react';
import { forecastMetrics } from '../lib/game/forecast';
import { bcgProfile } from '../lib/game/scoring';

const card = 'rounded-2xl border p-5 shadow-sm';
export default function MagicAnalytics({ state }: { state: any }) {
  const [timeQuarter, setTimeQuarter] = useState(state.q);
  const forecast = useMemo(() => forecastMetrics(state), [state]);
  const dna = { ambition: Math.min(100, state.roi + state.innovation), people: state.adoption + state.alloc.people * 2, governance: state.compliance + 100 - state.risk, data: state.data, resilience: state.satisfaction + state.literacy, balance: 100 - Math.abs(50 - state.alloc.people) * 1.2 };
  const profile = bcgProfile(state); const history = state.history || []; const past = history.find((entry: any) => entry.q === timeQuarter);
  const failures = [state.risk > 35 && 'Risk exposure is above the board threshold.', state.adoption < 50 && 'Adoption is lagging behind investment ambition.', state.data < 60 && 'Data readiness may constrain scale.'].filter(Boolean) as string[];
  return <div className="space-y-5">
    <section className={`${card} border-sky-400/30 bg-sky-400/10`}><div className="flex items-center justify-between"><div><h3 className="font-bold text-sky-200">Time Machine</h3><p className="mt-1 text-xs text-white/55">Revisit a previous decision point.</p></div><span className="rounded-full bg-sky-400/20 px-2 py-1 text-xs font-bold text-sky-200">Q{timeQuarter}</span></div><input aria-label="Time Machine quarter" type="range" min="1" max={Math.max(1, state.q)} value={timeQuarter} onChange={e => setTimeQuarter(Number(e.target.value))} className="mt-4 w-full accent-[#38bdf8]" />{past && <p className="mt-3 rounded-lg bg-black/10 p-3 text-xs text-white/70">Chosen: {past.chosen?.join(', ') || 'No recorded initiatives'}</p>}</section>
    <section className={`${card} border-fuchsia-400/30 bg-fuchsia-400/10`}><h3 className="font-bold text-fuchsia-200">Strategy DNA</h3><p className="mt-1 text-xs text-white/55">Your decision pattern across six leadership dimensions.</p><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(dna).map(([key, value]) => <div key={key}><div className="flex justify-between text-[10px] text-white/60"><span className="capitalize">{key}</span><b className="text-fuchsia-200">{Math.round(value as number)}</b></div><div className="mt-1 h-2 rounded bg-black/15"><div className="h-full rounded bg-fuchsia-300" style={{ width: `${Math.min(100, Math.max(0, value as number))}%` }} /></div></div>)}</div></section>
    <section className={`${card} border-emerald/30 bg-emerald/10`}><h3 className="font-bold text-emerald">Predictive forecast</h3><p className="mt-1 text-xs text-white/55">Local projection from people, data, governance, and trajectory.</p><div className="mt-4 space-y-3">{forecast.map(item => <div key={item.quarter} className="grid grid-cols-[34px_1fr_45px] items-center gap-2 text-xs"><span className="text-white/45">Q{item.quarter}</span><div className="h-3 rounded bg-black/15"><div className="h-full rounded bg-emerald" style={{ width: `${item.roi}%` }} /></div><span className="text-right text-emerald">{item.roi.toFixed(0)}%</span></div>)}</div></section>
    <section className={`${card} border-amber-400/30 bg-amber-400/10`}><h3 className="font-bold text-amber-200">Decision heatmap</h3><p className="mt-1 text-xs text-white/55">Historical choices and their current operating signals.</p><div className="mt-4 grid grid-cols-4 gap-1 text-center text-[10px]"><span /><span className="text-white/45">ROI</span><span className="text-white/45">Adopt</span><span className="text-white/45">Risk</span>{history.slice(-8).map((entry: any) => <div key={entry.q} className="contents"><span className="py-2 text-white/45">Q{entry.q}</span><span className="rounded bg-emerald/30 py-2 text-emerald">{entry.metrics?.roi > 0 ? '●' : '○'}</span><span className="rounded bg-fuchsia-400/30 py-2 text-fuchsia-200">{entry.metrics?.adoption >= state.adoption ? '●' : '○'}</span><span className="rounded bg-amber-400/30 py-2 text-amber-200">{entry.metrics?.risk <= state.risk ? '●' : '○'}</span></div>)}</div></section>
    <section className={`${card} border-rose-400/30 bg-rose-400/10`}><h3 className="font-bold text-rose-200">Failure analysis</h3>{failures.length ? <ul className="mt-3 space-y-2 text-xs text-white/70">{failures.map(failure => <li key={failure} className="rounded-lg bg-rose-950/30 p-3">⚠ {failure}</li>)}</ul> : <p className="mt-3 text-xs text-emerald">No critical failure pattern detected.</p>}<p className="mt-3 text-[10px] text-white/45">Weakest capability: {state.data < state.adoption ? 'data readiness' : state.risk > 35 ? 'governance' : 'adoption'}.</p></section>
    <section className={`${card} border-violet-400/30 bg-violet-400/10`}><h3 className="font-bold text-violet-200">BCG 10-20-70 benchmark</h3><div className="mt-4 flex h-5 overflow-hidden rounded"><div className="bg-violet-400" style={{ width: `${profile.people}%` }} /><div className="bg-emerald" style={{ width: `${profile.tech}%` }} /><div className="bg-amber-400" style={{ width: `${profile.process}%` }} /></div><div className="mt-2 grid grid-cols-3 text-[10px] text-white/55"><span>People {profile.people}%</span><span>Technology {profile.tech}%</span><span>Process {profile.process}%</span></div><p className="mt-3 text-xs text-white/70">Educational score influence: <b className="text-violet-200">+{profile.score}/5</b></p></section>
  </div>;
}
