'use client';
import { useMemo, useState } from 'react';
import { forecastMetrics } from '../lib/game/forecast';
import { bcgProfile } from '../lib/game/scoring';

export default function MagicAnalytics({ state }: { state: any }) {
  const [timeQuarter, setTimeQuarter] = useState(state.q);
  const forecast = useMemo(() => forecastMetrics(state), [state]);
  const dna = { ambition: Math.min(100, state.roi + state.innovation), people: state.adoption + state.alloc.people * 2, governance: state.compliance + 100 - state.risk, data: state.data, resilience: state.satisfaction + state.literacy, balance: 100 - Math.abs(50 - state.alloc.people) * 1.2 };
  const profile = bcgProfile(state);
  const history = state.history || [];
  const failures = [state.risk > 35 && 'Risk exposure is above the board threshold.', state.adoption < 50 && 'Adoption is lagging behind the investment ambition.', state.data < 60 && 'Data readiness may constrain scale.'].filter(Boolean) as string[];
  const past = (state.history || []).find((entry: any) => entry.q === timeQuarter);
  return <div className="space-y-4">
    <section className="rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center justify-between"><h3 className="font-bold text-emerald">Time Machine</h3><span className="text-xs text-white/45">Q{timeQuarter}</span></div><input aria-label="Time Machine quarter" type="range" min="1" max={Math.max(1, state.q)} value={timeQuarter} onChange={(e) => setTimeQuarter(Number(e.target.value))} className="mt-3 w-full accent-[#08872b]" /><p className="mt-2 text-xs text-white/55">Review an earlier decision point and compare the initiative set with today’s trajectory.</p>{past && <p className="mt-2 rounded bg-white/5 p-2 text-xs text-white/65">Q{past.q}: {past.chosen?.join(', ') || 'No recorded initiatives'}</p>}</section>
    <section className="rounded-xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-emerald">Strategy DNA</h3><p className="mt-1 text-xs text-white/50">Your current decision pattern across six leadership dimensions.</p><div className="mt-4 grid grid-cols-2 gap-2">{Object.entries(dna).map(([key, value]) => <div key={key}><div className="flex justify-between text-[10px] text-white/55"><span className="capitalize">{key}</span><b className="text-emerald">{Math.round(value as number)}</b></div><div className="mt-1 h-2 rounded bg-white/10"><div className="h-full rounded bg-emerald" style={{ width: `${Math.min(100, Math.max(0, value as number))}%` }} /></div></div>)}</div></section>
    <section className="rounded-xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-emerald">Predictive forecast</h3><p className="mt-1 text-xs text-white/50">Local projection based on people, data, governance, and current trajectory.</p><div className="mt-4 space-y-3">{forecast.map((item) => <div key={item.quarter} className="grid grid-cols-[34px_1fr_45px] items-center gap-2 text-xs"><span className="text-white/45">Q{item.quarter}</span><div className="h-3 rounded bg-white/10"><div className="h-full rounded bg-emerald" style={{ width: `${item.roi}%` }} /></div><span className="text-right text-emerald">{item.roi.toFixed(0)}%</span></div>)}</div></section>
    <section className="rounded-xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-emerald">Decision heatmap</h3><p className="mt-1 text-xs text-white/50">Green cells show where your choices are creating momentum.</p><div className="mt-3 grid grid-cols-4 gap-1 text-center text-[10px]"><span /><span className="text-white/45">ROI</span><span className="text-white/45">Adopt</span><span className="text-white/45">Risk</span>{history.slice(-6).map((entry: any, index: number) => <div key={index} className="contents"><span className="py-2 text-white/45">Q{entry.q}</span><span className="rounded bg-emerald/30 py-2 text-emerald">{state.roi > 20 ? '●' : '○'}</span><span className="rounded bg-purple-500/30 py-2 text-purple-200">{state.adoption > 50 ? '●' : '○'}</span><span className="rounded bg-gold/30 py-2 text-gold">{state.risk < 30 ? '●' : '○'}</span></div>)}</div></section>
    <section className="rounded-xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-emerald">Failure analysis</h3>{failures.length ? <ul className="mt-3 space-y-2 text-xs text-white/65">{failures.map((failure) => <li key={failure} className="rounded bg-crimson/15 p-2">⚠ {failure}</li>)}</ul> : <p className="mt-3 text-xs text-emerald">No critical failure pattern detected.</p>}<p className="mt-3 text-[10px] text-white/40">Review the next decision through the lens of the weakest operating capability.</p></section>
    <section className="rounded-xl border border-white/10 bg-white/5 p-4"><h3 className="font-bold text-emerald">BCG 10-20-70 benchmark</h3><div className="mt-3 flex h-5 overflow-hidden rounded"><div className="bg-purple-500" style={{ width: `${profile.people}%` }} /><div className="bg-emerald" style={{ width: `${profile.tech}%` }} /><div className="bg-gold" style={{ width: `${profile.process}%` }} /></div><div className="mt-2 grid grid-cols-3 text-[10px] text-white/55"><span>People {profile.people}%</span><span>Technology {profile.tech}%</span><span>Process {profile.process}%</span></div><p className="mt-3 text-xs text-white/65">Educational score influence: <b className="text-emerald">+{profile.score}/5</b>. The benchmark informs reflection; it does not block play.</p></section>
  </div>;
}
