'use client';

import { useMemo, useState, type CSSProperties } from 'react';
import { BarChart3, LineChart, ShieldCheck } from 'lucide-react';
import { forecastMetrics } from '../lib/game/forecast';
import { bcgProfile } from '../lib/game/scoring';
import { analyticsHistory, analyticsMetrics, portfolioDecisionProfile, scenarioForecast } from '../lib/analyticsViewModel';
import { getScenario } from '../lib/scenarios/registry';

const card = 'rounded-2xl border p-5 shadow-sm';
const clamp = (value: number) => Math.max(0, Math.min(100, value));

function heatCellStyle(value: number, metric: { direction: string }): CSSProperties {
  const normalized = clamp(value) / 100;
  const strength = metric.direction === 'lower-is-better' ? 1 - normalized : normalized;
  const hue = 210 - strength * 155;
  const lightness = 24 + strength * 22;
  return { backgroundColor: `hsl(${hue} 72% ${lightness}%)`, borderColor: `hsl(${hue} 80% ${Math.min(75, lightness + 20)}% / .7)`, color: strength > 0.55 ? '#ffffff' : '#d0d7de' };
}

function RoiChart({ points }: { points: { quarter: number; value: number }[] }) {
  const width = 560; const height = 190; const pad = 28;
  const x = (index: number) => pad + (index * (width - pad * 2)) / Math.max(1, points.length - 1);
  const y = (value: number) => height - pad - (clamp(value) / 100) * (height - pad * 2);
  const path = points.map((point, index) => `${index ? 'L' : 'M'} ${x(index)} ${y(point.value)}`).join(' ');
  return <div className="mt-4 overflow-hidden rounded-xl bg-black/15 p-2"><svg viewBox={`0 0 ${width} ${height}`} className="h-48 w-full" role="img" aria-label="ROI by quarter line chart"><path d={`M ${pad} ${y(0)} H ${width - pad}`} stroke="rgba(255,255,255,.12)"/><path d={`M ${pad} ${y(50)} H ${width - pad}`} stroke="rgba(255,255,255,.12)" strokeDasharray="4 4"/><path d={`M ${pad} ${y(100)} H ${width - pad}`} stroke="rgba(255,255,255,.12)"/><text x="3" y={y(100) + 4} fill="rgba(255,255,255,.4)" fontSize="10">100%</text><text x="10" y={y(50) + 4} fill="rgba(255,255,255,.4)" fontSize="10">50%</text><text x="18" y={y(0) + 4} fill="rgba(255,255,255,.4)" fontSize="10">0%</text><path d={path} fill="none" stroke="#34d399" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/>{points.map(point => <g key={point.quarter}><circle cx={x(points.indexOf(point))} cy={y(point.value)} r="5" fill="#0d1117" stroke="#34d399" strokeWidth="3"/><text x={x(points.indexOf(point))} y={height - 7} textAnchor="middle" fill="rgba(255,255,255,.55)" fontSize="10">Q{point.quarter}</text><text x={x(points.indexOf(point))} y={y(point.value) - 10} textAnchor="middle" fill="#a7f3d0" fontSize="10">{point.value.toFixed(1)}%</text></g>)}</svg></div>;
}

function DecisionHeatmap({ state }: { state: any }) {
  const metrics = analyticsMetrics(state);
  const entries: any[] = state.history || [];
  if (!entries.length) return <section className={`${card} border-amber-400/30 bg-amber-400/10`}><div className="flex items-center gap-2"><BarChart3 size={17} className="text-amber-200"/><h3 className="font-bold text-amber-200">Decision heatmap</h3></div><p className="mt-1 text-xs text-white/55">Complete a quarter to compare decision outcomes against the active scenario targets.</p><div className="mt-4 rounded-xl bg-black/15 p-5 text-center text-xs text-white/55">No recorded quarter yet.</div></section>;
  const visible = entries.slice(-8);
  const gridStyle: CSSProperties = { gridTemplateColumns: `150px repeat(${visible.length}, minmax(56px, 1fr))` };
  return <section className={`${card} border-amber-400/30 bg-amber-400/10`}><div className="flex items-center gap-2"><BarChart3 size={17} className="text-amber-200"/><h3 className="font-bold text-amber-200">Decision heatmap</h3></div><p className="mt-1 text-xs text-white/55">Color shows progress toward each metric’s target. Each cell is tied to the initiatives selected in that quarter.</p><div className="mt-4 overflow-x-auto"><div className="min-w-[520px] space-y-2"><div className="grid gap-1 text-center text-[10px] text-white/45" style={gridStyle}><span className="self-center text-left">Scenario metric</span>{visible.map(entry => <span key={entry.q}>Q{entry.q}</span>)}</div>{metrics.map(metric => <div key={metric.key} className="grid gap-1 text-center text-[11px]" style={gridStyle}><span className="self-center text-left font-medium text-white/65">{metric.label}</span>{visible.map(entry => { const value = metric.source === 'scenario' ? Number(entry.scenarioState?.metrics?.[metric.key] ?? metric.start) : Number(entry.metrics?.[metric.key] ?? metric.start); const moved = metric.direction === 'higher-is-better' ? value - metric.start : metric.start - value; const progress = Math.max(0, Math.min(100, (moved / Math.max(1, Math.abs(metric.target - metric.start))) * 100)); const chosen = entry.chosen?.join(', ') || 'No initiative recorded'; return <span key={`${metric.key}-${entry.q}`} title={`Q${entry.q} ${metric.label}: ${value.toFixed(1)} ${metric.unit}. Decision: ${chosen}`} className="rounded-md border px-1 py-3 font-bold shadow-sm transition-transform hover:scale-[1.03]" style={heatCellStyle(progress, { direction: 'higher-is-better' })}>{value.toFixed(metric.unit === '%' ? 0 : 1)}{metric.unit === '%' ? '%' : ''}</span>; })}</div>)}</div><div className="mt-4 flex items-center justify-between gap-3 text-[10px] text-white/50"><span>Behind target</span><div className="h-2 flex-1 rounded-full bg-gradient-to-r from-[#cf222e] via-[#d29922] to-[#1a7f37]"/><span>Near target</span></div><p className="mt-2 text-[10px] text-white/45">Showing {visible.length} of {entries.length} completed quarters · color is target progress, not raw magnitude.</p></div></section>;
}

export default function MagicAnalytics({ state }: { state: any }) {
  const [timeQuarter, setTimeQuarter] = useState(state.q);
  const forecast = useMemo(() => forecastMetrics(state), [state]);
  const scenario = state.scenarioMode ? getScenario(state.scenarioId) : undefined;
  const metrics = analyticsMetrics(state);
  const history = state.history || [];
  const roiHistory = analyticsHistory(state, { key: 'roi', label: 'ROI', unit: '%', current: state.roi, start: 0, target: 35, min: 0, max: 100, direction: 'higher-is-better', progress: 0, delta: state.roi, source: 'native', status: 'measured', provenance: 'derived', confidence: 'medium', sourceDetail: 'Native operating metric.' });
  const chartPoints = [...roiHistory, { quarter: state.q, value: Number(state.roi || 0) }].filter((point, index, all) => index === all.findIndex(other => other.quarter === point.quarter));
  const past = history.find((entry: any) => entry.q === timeQuarter);
  const avgPeople = history.length ? history.reduce((sum: number, entry: any) => sum + Number(entry.allocation?.people ?? 0), 0) / history.length : Number(state.alloc?.people || 0);
  const avgCompliance = history.length ? history.reduce((sum: number, entry: any) => sum + Number(entry.allocation?.compliance ?? 0), 0) / history.length : Number(state.alloc?.compliance || 0);
  const decisionProfile = portfolioDecisionProfile(state);
  const profile = bcgProfile(state);
  const scenarioProjection = scenario ? scenarioForecast(state) : [];
  const latest = history.at(-1);
  const failures = metrics.filter(metric => metric.progress < 35).map(metric => {
    const challenge = scenario?.challenges.find((item: any) => item.metric === metric.key);
    const selected = latest?.chosen?.filter((name: string) => name.toLowerCase().includes(metric.label.split(' ')[0].toLowerCase())) || [];
    const reason = challenge ? ` Challenge: ${challenge.description}` : '';
    const evidence = latest?.scenarioState?.metrics?.[metric.key] !== undefined ? ` Latest recorded value: ${Number(latest.scenarioState.metrics[metric.key]).toFixed(metric.unit === '%' ? 0 : 1)}${metric.unit === '%' ? '%' : ` ${metric.unit}`}.` : '';
    return `${metric.label} is only ${metric.progress.toFixed(0)}% toward target.${reason}${evidence}${selected.length ? ` Related decision: ${selected.join(', ')}.` : ''}`;
  });
  const weakestMetric = metrics.reduce((weakest, metric) => !weakest || metric.progress < weakest.progress ? metric : weakest, metrics[0]);
  return <div className="space-y-5">
    <section className={`${card} border-sky-400/30 bg-sky-400/10`}><div className="flex items-center justify-between"><div><h3 className="font-bold text-sky-200">Time Machine</h3><p className="mt-1 text-xs text-white/55">Revisit the decision, allocation and metric state at a prior quarter.</p></div><span className="rounded-full bg-sky-400/20 px-2 py-1 text-xs font-bold text-sky-200">Q{timeQuarter}</span></div><input aria-label="Time Machine quarter" type="range" min="1" max={Math.max(1, state.q)} value={timeQuarter} onChange={e => setTimeQuarter(Number(e.target.value))} className="mt-4 w-full accent-[#38bdf8]"/>{past && <div className="mt-3 rounded-lg bg-black/10 p-3 text-xs text-white/70"><p>Chosen: {past.chosen?.join(', ') || 'No recorded initiatives'}</p><p className="mt-1 text-white/45">Allocation: people {past.allocation?.people ?? '—'}% · data {past.allocation?.data ?? '—'}% · compliance {past.allocation?.compliance ?? '—'}%</p></div>}</section>
    <section className={`${card} border-fuchsia-400/30 bg-fuchsia-400/10`}><h3 className="font-bold text-fuchsia-200">Decision pattern</h3><p className="mt-1 text-xs text-white/55">Trends focuses on movement. Strategic identity and interpretation live in the DNA tab.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-[10px] text-white/45">Latest posture</p><b className="mt-1 block text-fuchsia-100">{decisionProfile.latest?.posture || 'Awaiting evidence'}</b></div><div><p className="text-[10px] text-white/45">Average selected</p><b className="mt-1 block text-fuchsia-100">{decisionProfile.averageSelected.toFixed(1)}</b></div><div><p className="text-[10px] text-white/45">Breadth</p><b className="mt-1 block text-fuchsia-100">{decisionProfile.breadth}%</b></div><div><p className="text-[10px] text-white/45">Pace</p><b className="mt-1 block text-fuchsia-100">{decisionProfile.paceStatus}</b></div></div><p className="mt-3 text-[10px] text-white/45">Measured from {history.length} completed-quarter decisions and spend.</p></section>
    <section className={`${card} border-emerald/30 bg-emerald/10`}><div className="flex items-center gap-2"><LineChart size={17} className="text-emerald"/><h3 className="font-bold text-emerald">Portfolio ROI trend</h3></div><p className="mt-1 text-xs text-white/55">Portfolio ROI only. Use the heatmap and scenario scorecard for domain outcomes.</p>{chartPoints.length > 1 ? <RoiChart points={chartPoints}/> : <div className="mt-4 rounded-xl bg-black/15 p-5 text-center text-xs text-white/55">Complete your first quarter to create the trend line. Current ROI: <b className="text-emerald">{Number(state.roi || 0).toFixed(1)}%</b></div>}</section>
    <DecisionHeatmap state={state}/>
    <section className={`${card} border-emerald/30 bg-emerald/10`}><div className="flex items-center justify-between gap-3"><h3 className="font-bold text-emerald">{scenario ? `${scenario.name} outcome projection` : 'Trajectory projection'}</h3><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] uppercase tracking-wide text-white/55">Modelled proxy</span></div><p className="mt-1 text-xs text-white/55">{scenario ? 'Directional model using recorded momentum, target gap, and relevant funding signal. It is not measured telemetry.' : 'Directional model—not measured telemetry. Native ROI remains separate from scenario outcomes.'}</p>{scenario ? <div className="mt-4 space-y-3">{scenarioProjection.map(point => <div key={point.quarter} className="rounded-lg bg-black/15 p-3"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-wider text-sky-200">Q{point.quarter}</p><span className="text-[10px] text-white/45">{point.confidence} confidence · {history.length} completed quarter{history.length === 1 ? '' : 's'}</span></div><div className="mt-2 flex flex-wrap gap-2">{metrics.map(metric => { const range = point.ranges[metric.key]; return <span key={metric.key} title={`Modelled range: ${range ? `${range.low.toFixed(1)}–${range.high.toFixed(1)}` : 'not available'}`} className="rounded bg-sky-400/15 px-2 py-1 text-[10px] text-sky-100">{metric.label}: {Number(point.values[metric.key]).toFixed(metric.unit === '%' ? 0 : 1)}{metric.unit === '%' ? '%' : ` ${metric.unit}`} {range ? <em className="not-italic text-sky-200/60">({range.low.toFixed(0)}–{range.high.toFixed(0)})</em> : null}</span>; })}</div></div>)}</div> : <div className="mt-4 space-y-3">{forecast.map(item => <div key={item.quarter} className="rounded-lg bg-black/10 p-2"><div className="flex items-center justify-between text-xs"><span className="text-white/45">Q{item.quarter}</span><span className="text-white/45">{item.confidence} confidence · {item.ranges.roi.low.toFixed(0)}–{item.ranges.roi.high.toFixed(0)}%</span><span className="text-right text-emerald">{item.roi.toFixed(0)}%</span></div><div className="mt-1 h-3 rounded bg-black/15"><div className="h-full rounded bg-emerald" style={{ width: `${item.roi}%` }}/></div></div>)}</div>}</section>
    <section className={`${card} border-rose-400/30 bg-rose-400/10`}><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-rose-200"/><h3 className="font-bold text-rose-200">Failure analysis</h3></div>{failures.length ? <ul className="mt-3 space-y-2 text-xs text-white/70">{failures.map(failure => <li key={failure} className="rounded-lg bg-rose-950/30 p-3">⚠ {failure}</li>)}</ul> : <p className="mt-3 text-xs text-emerald">No {scenario ? 'scenario' : 'portfolio'} metric is materially behind target.</p>}<p className="mt-3 text-[10px] text-white/45">Weakest metric: {weakestMetric?.label || 'not available'} · {scenario ? `${scenario.name}; gaps are evaluated against its native targets.` : 'Standard portfolio'}.</p></section>
    <section className={`${card} border-violet-400/30 bg-violet-400/10`}><h3 className="font-bold text-violet-200">BCG 10-20-70 benchmark</h3><div className="mt-4 flex h-5 overflow-hidden rounded"><div className="bg-violet-400" style={{ width: `${profile.people}%` }}/><div className="bg-emerald" style={{ width: `${profile.tech}%` }}/><div className="bg-amber-400" style={{ width: `${profile.process}%` }}/></div><div className="mt-2 grid grid-cols-3 text-[10px] text-white/55"><span>People {profile.people}%</span><span>Technology {profile.tech}%</span><span>Process {profile.process}%</span></div><p className="mt-3 text-xs text-white/70">Educational score influence: <b className="text-violet-200">+{profile.score}/5</b></p></section>
  </div>;
}
