'use client';
import { ArrowRight, CircleDollarSign, GitBranch } from 'lucide-react';
import { formatCurrency } from '../lib/currency';
const fmt = (value: number) => Number(value.toFixed(2)).toString();
export default function QuarterRoadmap({ state }: { state: any }) {
  const history = state.history || [];
  if (!history.length) return <div className="rounded-xl border border-white/10 bg-white/5 p-5 text-sm text-white/55">The roadmap will populate after the first completed quarter.</div>;
  return <section className="rounded-2xl border border-sky-400/30 bg-sky-400/10 p-5"><div className="flex items-center gap-2"><GitBranch size={17} className="text-sky-200"/><div><b>Quarter roadmap</b><p className="text-xs text-white/50">A sequence of what was funded, what changed, and what carried forward.</p></div></div><div className="mt-5 overflow-x-auto pb-2"><div className="flex min-w-max items-stretch gap-2">{history.map((entry: any, index: number) => { const previous = history[index - 1]; const spend = Number(entry.metrics?.spent ?? 0) - Number(previous?.metrics?.spent ?? 0); const firstQuarterSpend = Number(entry.metrics?.spent ?? 0); const roiDelta = Number(entry.metrics?.roi ?? 0) - Number(previous?.metrics?.roi ?? 0); const scenarioValues = entry.scenarioState?.metrics ? Object.entries(entry.scenarioState.metrics).slice(0, 2).map(([key, value]) => `${key}: ${Number(value).toFixed(1)}`).join(' · ') : ''; return <div key={entry.q} className="flex items-center gap-2"><article className="w-56 rounded-xl border border-white/10 bg-ink/60 p-3"><div className="flex items-center justify-between"><b className="text-sky-200">Q{entry.q}</b><span className="text-[10px] text-white/45">{entry.chosen?.length || 0} bets</span></div><p className="mt-3 line-clamp-2 text-xs font-bold text-white/80">{entry.chosen?.join(' · ') || 'No initiative recorded'}</p><div className="mt-3 flex items-center justify-between text-[10px]"><span className="flex items-center gap-1 text-gold"><CircleDollarSign size={12}/> +{formatCurrency(Math.max(0, index === 0 ? firstQuarterSpend : spend), state.currencyMode)}</span><span className={roiDelta >= 0 ? 'text-emerald' : 'text-rose-200'}>{roiDelta >= 0 ? '+' : ''}{fmt(roiDelta)} ROI</span></div>{scenarioValues && <p className="mt-2 line-clamp-2 text-[9px] text-sky-200">{scenarioValues}</p>}<p className="mt-2 text-[9px] text-white/40">{entry.initiativeStates ? 'State captured' : 'Legacy snapshot'}</p></article>{index < history.length - 1 && <ArrowRight size={16} className="shrink-0 text-sky-300"/>}</div>; })}</div></div></section>;
}
