'use client';

import { AlertTriangle, Check, CheckCircle2, CircleX, FlaskConical, RotateCcw, Save, Target, Wallet, X, Zap } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useGameStore } from '../stores/gameStore';
import { formatCurrency } from '../lib/currency';
import { getScenario } from '../lib/scenarios/registry';
import { previewStrategy, type StrategyPreview, type StrategyPreviewMetric } from '../lib/game/strategyPreview';
import { deploymentCapacity } from '../lib/game/state';

type Props = { state: any; initiatives: any[]; onClose: () => void };
type AllocationKey = 'infra' | 'data' | 'people' | 'mlops' | 'compliance' | 'innovation';

const labels: Record<AllocationKey, string> = {
  infra: 'Infrastructure', data: 'Data', people: 'People', mlops: 'Ops & maintenance', compliance: 'Governance', innovation: 'Innovation',
};
const n = (value: unknown, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const metricValue = (value: number, unit: string) => `${value.toFixed(1)}${unit === '%' ? '%' : ` ${unit}`}`;
const metricDelta = (value: number, unit: string) => `${value >= 0 ? '+' : ''}${value.toFixed(1)}${unit === '%' ? ' pts' : ` ${unit}`}`;
const isImprovement = (item: StrategyPreviewMetric) => item.direction === 'lower-is-better' ? item.delta < -0.05 : item.delta > 0.05;

function OutcomeRow({ item, emphasis = false }: { item: StrategyPreviewMetric; emphasis?: boolean }) {
  const better = isImprovement(item);
  const worse = item.direction === 'lower-is-better' ? item.delta > 0.05 : item.delta < -0.05;
  const tone = better ? 'border-[#1a7f37]/25 bg-[#dafbe1]/45' : worse ? 'border-[#cf222e]/25 bg-[#ffebe9]/55' : 'border-[#d0d7de] bg-white';
  const Icon = better ? CheckCircle2 : worse ? CircleX : Target;
  return <article className={`rounded-xl border p-3 ${tone}`}>
    <div className="flex items-start justify-between gap-3">
      <div className="min-w-0"><p className="text-xs font-bold text-[#24292f]">{item.label}</p><p className="mt-1 text-[11px] text-[#57606a]">{metricValue(item.current, item.unit)} → <b className="text-[#24292f]">{metricValue(item.alternative, item.unit)}</b></p></div>
      <span className={`flex shrink-0 items-center gap-1 text-xs font-bold ${better ? 'text-[#1a7f37]' : worse ? 'text-[#cf222e]' : 'text-[#57606a]'}`}><Icon size={14} /> {Math.abs(item.delta) < 0.05 ? 'No material change' : metricDelta(item.delta, item.unit)}</span>
    </div>
    {emphasis && <p className={`mt-2 text-[10px] font-medium ${better ? 'text-[#1a7f37]' : worse ? 'text-[#cf222e]' : 'text-[#57606a]'}`}>{better ? 'Improves this operating pressure.' : worse ? 'Worsens this operating pressure.' : 'This plan does not materially move this pressure.'}</p>}
  </article>;
}

export default function StrategySimulator({ state, initiatives, onClose }: Props) {
  const scenario = state.scenarioMode ? getScenario(state.scenarioId) : undefined;
  const [selected, setSelected] = useState<string[]>(state.selected || []);
  const [alloc, setAlloc] = useState({ ...state.alloc });
  const [deployment, setDeployment] = useState(n(state.deploymentAmount));
  const [name, setName] = useState('Untitled strategy');
  const [saved, setSaved] = useState<any[]>([]);
  const [applied, setApplied] = useState(false);
  const total = Object.values(alloc).reduce((sum: number, value) => sum + n(value), 0);
  const currency = state.currencyMode || scenario?.currency.defaultSymbol || '$';
  const capacity = deploymentCapacity(n(state.campaignBudget, n(state.quarterlyBudget) * 12), n(state.campaignBudgetRemaining, n(state.campaignBudget, n(state.quarterlyBudget) * 12)), n(state.quarterlyBudget), n(state.q, 1), n(state.spent));
  const maxDeployment = capacity.maximumDeployment;
  const effectiveDeployment = Math.min(Math.max(0, deployment), maxDeployment);
  const preview = useMemo<StrategyPreview>(() => previewStrategy(state, { selected, alloc, deploymentAmount: effectiveDeployment, initiativeActions: state.initiativeActions }), [state, selected, alloc, effectiveDeployment]);
  const scenarioMetricKeys = new Set(scenario?.progress.map((definition) => definition.key) || []);
  const keyOutcomes = scenario ? preview.metricDeltas.filter((item) => scenarioMetricKeys.has(item.key)) : preview.metricDeltas.slice(0, 5);
  const selectedNames = selected.map((id) => initiatives.find((item) => item.id === id)?.name).filter(Boolean);
  const allocationSignals = [
    n(alloc.people) < 15 ? 'People is below the engine’s 15% readiness threshold; adoption gains will be constrained.' : null,
    n(alloc.compliance) < 10 ? 'Governance is below the engine’s 10% risk-control threshold; risk relief will be constrained.' : null,
    n(alloc.data) < 15 ? 'Data is light for a data-dependent plan; value realisation will be slower.' : null,
  ].filter((signal): signal is string => Boolean(signal));
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 3 ? [...current, id] : current);
  const apply = () => {
    if (!preview.valid || total !== 100) return;
    useGameStore.getState().applyWhatIfDraft({ name, selected, alloc, deploymentAmount: effectiveDeployment, initiativeActions: preview.alternative.decision?.initiativeActions, projection: preview, quarter: state.q });
    setApplied(true);
  };
  const reset = () => { setSelected([]); setAlloc({ ...state.alloc }); setDeployment(Math.min(n(state.deploymentAmount), maxDeployment)); setName('Untitled strategy'); setApplied(false); };

  return <div className="command-overlay fixed inset-0 z-[60] overflow-y-auto p-3 sm:p-5 lg:p-8">
    <div className="command-modal command-simulator min-h-[calc(100vh-1.5rem)] w-full rounded-2xl sm:min-h-[calc(100vh-2.5rem)] lg:min-h-[calc(100vh-4rem)]">
      <header className="flex items-center justify-between border-b border-ink/10 bg-white px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald/10 p-2 text-emerald"><FlaskConical size={21}/></div><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald">Strategy laboratory · Q{state.q}</p><h2 className="text-xl font-bold sm:text-2xl">Explore before you commit</h2><p className="mt-1 text-xs text-ink/50">A deterministic preview using the same rules as the campaign. It changes nothing until you apply the draft.</p></div></div><button onClick={onClose} aria-label="Close strategy simulator" className="rounded-lg p-2 hover:bg-mist"><X size={20}/></button></header>
      <div className="grid w-full xl:grid-cols-[minmax(0,1fr)_minmax(340px,390px)]">
        <main className="min-w-0 p-5 sm:p-7 lg:p-9">
          <section className="rounded-2xl border border-[#0969da]/20 bg-[#ddf4ff]/65 p-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0969da]">Decision question</p><h3 className="mt-2 text-2xl font-bold tracking-[-.03em] text-[#24292f]">What problem are you solving this quarter?</h3><p className="mt-2 max-w-3xl text-sm leading-6 text-[#57606a]">{scenario ? `Choose a portfolio that deliberately moves ${scenario.name}'s active operating pressures. The preview shows the next-quarter consequence before you commit.` : 'Choose a portfolio that deliberately improves value, capability, and resilience. The preview shows the next-quarter consequence before you commit.'}</p>{scenario?.challenges?.length ? <div className="mt-4 flex flex-wrap gap-2">{scenario.challenges.slice(0, 4).map((challenge) => <span key={challenge.id} className="rounded-full border border-[#0969da]/20 bg-white px-3 py-1.5 text-xs font-semibold text-[#0969da]">{challenge.label}</span>)}</div> : null}</section>

          <section className="mt-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald">Predicted operating outcome</p><h3 className="mt-1 text-xl font-bold">Here is what this plan changes</h3></div><span className="rounded-full bg-white px-3 py-1.5 text-xs font-bold text-[#57606a] ring-1 ring-[#d0d7de]">Preview only · not committed</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{keyOutcomes.map((item) => <OutcomeRow key={item.key} item={item} emphasis />)}</div></section>

          <div className="mt-5 grid gap-4 xl:grid-cols-2">
            <section className="rounded-2xl border border-[#cf222e]/25 bg-[#ffebe9]/55 p-5"><div className="flex items-center gap-2"><AlertTriangle size={17} className="text-[#cf222e]"/><h4 className="font-bold text-[#24292f]">Pressures left uncovered</h4></div>{scenario && preview.uncovered.length ? <div className="mt-3 space-y-2">{scenario.progress.filter((definition) => preview.uncovered.includes(definition.label)).map((definition) => { const current = n(preview.current.scenarioMetrics[definition.key], definition.start); const alternative = n(preview.alternative.scenarioMetrics[definition.key], current); return <div key={definition.key} className="rounded-xl border border-[#cf222e]/15 bg-white p-3"><div className="flex justify-between gap-3 text-sm"><b>{definition.label}</b><span className="text-[#cf222e]">Target {metricValue(definition.target, definition.unit)}</span></div><p className="mt-1 text-xs text-[#57606a]">{metricValue(current, definition.unit)} → {metricValue(alternative, definition.unit)} · unchanged by this plan</p></div>; })}</div> : <p className="mt-3 text-sm leading-6 text-[#57606a]">{scenario ? 'This portfolio covers every scenario pressure directly.' : 'Standard mode has no scenario-specific pressure map. Review the outcome movement above.'}</p>}</section>
            <section className="rounded-2xl border border-[#d4a72c]/30 bg-[#fff8c5]/55 p-5"><div className="flex items-center gap-2"><Target size={17} className="text-[#9a6700]"/><h4 className="font-bold text-[#24292f]">Trade-offs and reflection</h4></div><div className="mt-3 space-y-2 text-sm leading-6 text-[#57606a]">{preview.tradeoffs.slice(0, 3).map((item) => <p key={item}>• {item}</p>)}</div><div className="mt-4 rounded-xl border border-[#d4a72c]/25 bg-white/75 p-3 text-sm leading-6 text-[#24292f]"><b>Ask yourself:</b> {preview.improves[0] && preview.worsens[0] ? `Is the ${preview.improves[0].label.toLowerCase()} gain worth the ${preview.worsens[0].label.toLowerCase()} deterioration — and is that trade-off intentional?` : preview.improves[0] ? `What would need to be true for the ${preview.improves[0].label.toLowerCase()} gain to be realised in practice?` : 'What evidence would justify holding capital rather than funding a bet now?'}</div></section>
          </div>

          <section className="strategy-bets-section mt-5 rounded-2xl border p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-ink/45">Choose the bets</p><h3 className="mt-1 text-xl font-bold">Which initiatives make this outcome plausible?</h3><p className="mt-1 text-xs leading-5 text-ink/55">Choose zero to three. A smaller portfolio creates focus; a broader portfolio covers more pressures and increases coordination demand.</p></div><span className="rounded-full bg-ink px-3 py-2 text-xs font-bold text-white">{selected.length}/3 bets</span></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{initiatives.map((item) => { const active = selected.includes(item.id); const live = state.initiativeStates?.[item.id] || item; const primaryMetric = live.scenarioMetadata?.primaryMetric; const definition = scenario?.progress.find((metric) => metric.key === primaryMetric); const direction = definition?.direction === 'lower-is-better' ? 'Reduce' : 'Improve'; return <button key={item.id} type="button" aria-pressed={active} onClick={() => toggle(item.id)} className={`strategy-bet-card ${active ? 'is-selected' : ''} group rounded-xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald ${active ? 'border-[#4ac26b] shadow-[0_0_0_1px_rgba(74,194,107,.22)]' : 'border-white/15 hover:border-[#5fca7c]'}`}><div className="flex items-start justify-between gap-3"><div><b className="block text-sm text-[#24292f]">{item.name}</b><p className="mt-2 text-xs leading-5 text-[#57606a]">{item.desc}</p></div><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${active ? 'border-[#4ac26b] bg-[#4ac26b] text-[#0d1710]' : 'border-white/25 text-transparent'}`}><Check size={13}/></span></div><div className="mt-4 border-t border-ink/10 pt-3 text-[11px] leading-5 text-[#57606a]"><p><b className="text-[#24292f]">Primary lever:</b> {definition ? `${direction} ${definition.label.toLowerCase()} (${live.scenarioMetadata?.baseEffect > 0 ? '+' : ''}${n(live.scenarioMetadata?.baseEffect)} ${live.scenarioMetadata?.effectUnit || definition.unit})` : item.impact}</p><p className="mt-1"><b className="text-[#24292f]">Quarter cost:</b> {formatCurrency(n(live.currentCost ?? item.cost), currency)} · <b className="text-[#24292f]">Data:</b> {n(live.currentData ?? item.data).toFixed(1)}/5 · <b className="text-[#24292f]">Maturity:</b> {live.maturityLevel || 'nascent'}</p></div></button>; })}</div></section>

          <section className="mt-5 rounded-2xl border border-ink/10 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-ink/45">Decision comparison</p><h3 className="mt-1 text-xl font-bold">Current position → this alternative</h3></div><p className="text-xs text-ink/50">The arrows show the next-quarter engine preview.</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{preview.metricDeltas.slice(0, 7).map((item) => <OutcomeRow key={item.key} item={item} />)}</div></section>
        </main>

        <aside className="border-t border-ink/10 bg-white p-5 sm:p-7 xl:sticky xl:top-0 xl:h-screen xl:overflow-y-auto xl:border-l xl:border-t-0">
          <section className="rounded-2xl border border-[#d4a72c]/30 bg-[#fff8c5]/40 p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Wallet size={16} className="mt-0.5 text-[#9a6700]"/><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#9a6700]">Campaign capital to release this quarter</p><h3 className="mt-1 text-lg font-bold text-[#24292f]">Release capital intentionally</h3></div></div><b className="text-sm text-[#24292f]">{formatCurrency(effectiveDeployment, currency)}</b></div><input aria-label="Deployment amount" type="range" min="0" max={Math.max(0, maxDeployment)} step="0.1" value={effectiveDeployment} onChange={(event) => setDeployment(Number(event.target.value))} className="mt-4 w-full accent-[#d4a72c]"/><div className="mt-3 grid gap-2 text-xs"><p className="flex justify-between gap-3"><span className="text-[#57606a]">Total budget available now</span><b>{formatCurrency(capacity.campaignRemaining, currency)}</b></p><p className="flex justify-between gap-3"><span className="text-[#57606a]">Minimum quarterly funding</span><b>{formatCurrency(preview.alternative.spend.portfolioCost, currency)}</b></p><p className="flex justify-between gap-3"><span className="text-[#57606a]">Accelerated delivery capital</span><b className={preview.alternative.spend.acceleratedInvestment > 0 ? 'text-[#1a7f37]' : ''}>{formatCurrency(preview.alternative.spend.acceleratedInvestment, currency)}</b></p><p className="flex justify-between gap-3"><span className="text-[#57606a]">Delivery intensity</span><b>{preview.alternative.spend.fundingIntensity.toFixed(2)}×</b></p><p className="flex justify-between gap-3"><span className="text-[#57606a]">Campaign reserve after this plan</span><b>{formatCurrency(Math.max(0, capacity.campaignRemaining - preview.alternative.spend.amount), currency)}</b></p></div><p className="mt-3 rounded-lg bg-white/75 p-2.5 text-[11px] leading-5 text-[#57606a]">{preview.alternative.spend.acceleratedInvestment > 0 ? `The additional ${formatCurrency(preview.alternative.spend.acceleratedInvestment, currency)} is invested across the selected initiatives in proportion to their baseline cost. It accelerates next-quarter delivery with diminishing returns.` : effectiveDeployment < capacity.basePace ? `Below the planning pace of ${formatCurrency(capacity.basePace, currency)}. You are preserving optionality for future quarters.` : `At or above the planning pace of ${formatCurrency(capacity.basePace, currency)}. You are bringing more capital forward.`}</p></section>
          <section className="mt-4 rounded-2xl border border-ink/10 bg-[#f6f8fa] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#0969da]">Operating system</p><h3 className="mt-1 font-bold text-[#24292f]">Allocation · {total}%</h3></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${total === 100 ? 'bg-[#dafbe1] text-[#1a7f37]' : 'bg-[#ffebe9] text-[#cf222e]'}`}>{total === 100 ? 'Balanced' : 'Rebalance'}</span></div><div className="mt-4 space-y-3">{(Object.entries(alloc) as [AllocationKey, number][]).map(([key, value]) => <label key={key} className="block rounded-lg bg-white p-2.5 ring-1 ring-[#d8dee4] focus-within:ring-2 focus-within:ring-[#0969da]"><span className="flex justify-between gap-2 text-xs font-bold text-[#24292f]"><span>{labels[key]}</span><span>{value}%</span></span><input aria-label={`${key} allocation`} type="range" min="5" max="50" value={value} onChange={(event) => setAlloc((current: Record<string, number>) => ({ ...current, [key]: Number(event.target.value) }))} className="mt-2 w-full cursor-ew-resize accent-[#d4a72c]"/></label>)}</div>{total !== 100 && <p className="mt-3 rounded-lg bg-[#ffebe9] p-2 text-xs font-bold text-[#cf222e]">Rebalance to exactly 100% before applying.</p>}{allocationSignals.length ? <div className="mt-3 rounded-xl border border-[#0969da]/15 bg-[#ddf4ff]/60 p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#0969da]">Allocation implications</p>{allocationSignals.map((signal) => <p key={signal} className="mt-2 text-[11px] leading-5 text-[#57606a]">• {signal}</p>)}</div> : <p className="mt-3 rounded-xl bg-[#dafbe1]/60 p-3 text-[11px] leading-5 text-[#1a7f37]">Your allocation clears the engine’s people, governance, and data readiness thresholds.</p>}</section>
          <section className="mt-4 rounded-2xl border border-ink/10 bg-white p-4"><label className="block"><span className="text-[10px] font-bold uppercase tracking-[.14em] text-ink/45">Draft name</span><input aria-label="Strategy name" value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-lg border border-ink/10 bg-mist px-3 py-2 text-sm font-bold"/></label>{preview.warning ? <p className="mt-3 rounded-lg bg-[#ffebe9] p-3 text-xs font-bold leading-5 text-[#cf222e]">{preview.warning}</p> : null}<div className="mt-4 grid gap-2"><button onClick={apply} disabled={!preview.valid || total !== 100} className="flex w-full items-center justify-center gap-2 rounded-lg bg-ink px-4 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-35"><Zap size={15}/> Apply as next-quarter draft</button><button onClick={() => setSaved((current) => [...current, { name: name.trim() || 'Untitled strategy', selected, alloc, deployment: effectiveDeployment, preview }])} className="flex w-full items-center justify-center gap-2 rounded-lg border border-ink/15 bg-white px-4 py-3 text-sm font-bold"><Save size={15}/> Save experiment</button><button onClick={reset} className="flex w-full items-center justify-center gap-2 rounded-lg border border-ink/15 px-4 py-3 text-sm font-bold"><RotateCcw size={15}/> Reset</button></div>{applied && <p className="mt-3 rounded-lg bg-[#dafbe1] p-3 text-xs font-bold leading-5 text-[#1a7f37]">Draft applied: {selectedNames.length ? selectedNames.join(' · ') : 'reserve-only plan'}, capital, and allocation are now editable on the decision screen.</p>}</section>
          {saved.length > 0 && <section className="mt-4 border-t border-ink/10 pt-4"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-ink/45">Saved experiments</p><div className="mt-2 space-y-2">{saved.map((item, index) => <button key={`${item.name}-${index}`} onClick={() => { setName(item.name); setSelected(item.selected); setAlloc(item.alloc); setDeployment(Math.min(item.deployment, maxDeployment)); setApplied(false); }} className="w-full rounded-lg bg-[#f6f8fa] px-3 py-2 text-left text-xs font-bold text-[#24292f]">{item.name} · {item.preview.improves.length} gains · {item.selected.length} bets</button>)}</div></section>}
        </aside>
      </div>
    </div>
  </div>;
}
