'use client';

import { Check, FlaskConical, RotateCcw, Save, X, Zap } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useGameStore } from '../stores/gameStore';
import { formatCurrency } from '../lib/currency';
import { getScenario } from '../lib/scenarios/registry';
import { previewStrategy, type StrategyPreview } from '../lib/game/strategyPreview';

type Props = { state: any; initiatives: any[]; onClose: () => void };
type AllocationKey = 'infra' | 'data' | 'people' | 'mlops' | 'compliance' | 'innovation';
const labels: Record<AllocationKey, string> = { infra: 'Infrastructure', data: 'Data', people: 'People', mlops: 'Ops & maintenance', compliance: 'Governance', innovation: 'Innovation' };
const n = (value: unknown, fallback = 0) => Number.isFinite(Number(value)) ? Number(value) : fallback;
const delta = (value: number, unit: string) => `${value >= 0 ? '+' : ''}${value.toFixed(1)}${unit === '%' ? ' pts' : ` ${unit}`}`;

export default function StrategySimulator({ state, initiatives, onClose }: Props) {
  const scenario = state.scenarioMode ? getScenario(state.scenarioId) : undefined;
  const [selected, setSelected] = useState<string[]>(state.selected || []);
  const [alloc, setAlloc] = useState({ ...state.alloc });
  const [deployment, setDeployment] = useState(n(state.deploymentAmount));
  const [name, setName] = useState('Untitled strategy');
  const [saved, setSaved] = useState<any[]>([]);
  const [applied, setApplied] = useState(false);
  const total = Object.values(alloc).reduce((sum: number, value) => sum + n(value), 0);
  const preview = useMemo<StrategyPreview>(() => previewStrategy(state, { selected, alloc, deploymentAmount: deployment }), [state, selected, alloc, deployment]);
  const currency = state.currencyMode || scenario?.currency.defaultSymbol || '$';
  const maxDeployment = Math.max(0, n(state.campaignBudgetRemaining, n(state.campaignBudget, n(state.quarterlyBudget) * 12)));
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 3 ? [...current, id] : current);
  const apply = () => { if (!preview.valid || total !== 100) return; useGameStore.getState().applyWhatIfDraft({ name, selected, alloc, projection: preview, quarter: state.q }); setApplied(true); };
  const reset = () => { setSelected([]); setAlloc({ ...state.alloc }); setDeployment(n(state.deploymentAmount)); setName('Untitled strategy'); setApplied(false); };

  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-ink/75 p-3 backdrop-blur-sm sm:p-5 lg:p-8"><div className="min-h-[calc(100vh-1.5rem)] w-full rounded-2xl border border-ink/15 bg-mist shadow-2xl sm:min-h-[calc(100vh-2.5rem)] lg:min-h-[calc(100vh-4rem)]">
    <header className="flex items-center justify-between border-b border-ink/10 bg-white px-5 py-4 sm:px-7"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald/10 p-2 text-emerald"><FlaskConical size={21}/></div><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald">Strategy laboratory · Q{state.q}</p><h2 className="text-xl font-bold sm:text-2xl">Explore before you commit</h2><p className="mt-1 text-xs text-ink/50">A deterministic preview using the same quarter rules as the campaign.</p></div></div><button onClick={onClose} aria-label="Close strategy simulator" className="rounded-lg p-2 hover:bg-mist"><X size={20}/></button></header>
    <div className="grid min-h-[calc(100vh-8rem)] w-full lg:grid-cols-[minmax(300px,25%)_minmax(0,1fr)]"><section className="border-b border-ink/10 bg-white p-5 sm:p-7 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-ink/45">Draft name</p><input aria-label="Strategy name" value={name} onChange={event => setName(event.target.value)} className="mt-1 w-full rounded-lg border border-ink/10 bg-mist px-3 py-2 text-sm font-bold"/></div><span className="whitespace-nowrap rounded-full bg-ink px-3 py-2 text-xs font-bold text-white">{selected.length}/3 bets</span></div>
      <p className="mt-7 text-xs font-bold uppercase tracking-widest text-ink/45">Initiatives in this alternative</p><p className="mt-1 text-xs text-ink/50">Choose zero, one, two, or three. Focus is a strategic choice, not a constraint.</p><div className="mt-3 grid gap-2">{initiatives.map(item => { const active = selected.includes(item.id); return <button key={item.id} type="button" onClick={() => toggle(item.id)} className={`flex w-full items-center justify-between rounded-xl border p-3 text-left ${active ? 'border-emerald bg-emerald/8' : 'border-ink/10 bg-mist'}`}><span className="min-w-0"><b className="block truncate text-sm">{item.name}</b><small className="mt-1 block text-ink/50">{n(item.roi ?? item.currentRoi).toFixed(0)}% ROI · {n(item.riskScore ?? item.risk).toFixed(0)} risk</small></span><span className={`ml-3 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border ${active ? 'border-emerald bg-emerald text-ink' : 'border-ink/15 text-transparent'}`}><Check size={13}/></span></button>; })}</div>
      <p className="mt-7 text-xs font-bold uppercase tracking-widest text-ink/45">Deployment this quarter</p><div className="mt-3 rounded-xl border border-ink/10 bg-mist p-3"><div className="flex justify-between text-sm font-bold"><span>{formatCurrency(deployment, currency)}</span><span className="text-ink/45">{formatCurrency(maxDeployment, currency)} available</span></div><input aria-label="Deployment amount" type="range" min="0" max={Math.max(1, maxDeployment)} step="0.1" value={Math.min(deployment, maxDeployment)} onChange={event => setDeployment(Number(event.target.value))} className="mt-3 w-full accent-[#08872b]"/><p className="mt-2 text-[10px] text-ink/50">Preserve budget deliberately or deploy more now; the preview makes the trade-off visible.</p></div>
      <p className="mt-7 text-xs font-bold uppercase tracking-widest text-ink/45">Operating system allocation · {total}%</p><div className="mt-3 space-y-3">{(Object.entries(alloc) as [AllocationKey, number][]).map(([key, value]) => <label key={key} className="block text-xs"><span className="mb-1 flex justify-between font-bold"><span>{labels[key]}</span><span>{value}%</span></span><input aria-label={`${key} allocation`} type="range" min="5" max="50" value={value} onChange={event => setAlloc((current: Record<string, number>) => ({ ...current, [key]: Number(event.target.value) }))} className="w-full accent-[#08872b]"/></label>)}</div>{total !== 100 && <p className="mt-3 rounded-lg bg-crimson/10 p-2 text-xs font-bold text-crimson">Rebalance to exactly 100% before applying.</p>}
    </section><section className="min-w-0 p-5 sm:p-7 lg:p-9"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-widest text-emerald">Decision comparison</p><h3 className="mt-1 text-2xl font-bold sm:text-3xl">What changes if you choose this?</h3></div>{scenario && <span className="rounded-full bg-sky-100 px-3 py-2 text-xs font-bold text-sky-800">{scenario.name}</span>}</div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{preview.metricDeltas.slice(0, 4).map(item => <article key={item.key} className="rounded-xl border border-ink/10 bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-ink/45">{item.label}</p><div className="mt-2 flex items-end justify-between gap-2"><b className="text-2xl">{item.alternative.toFixed(1)}{item.unit === '%' ? '%' : ` ${item.unit}`}</b><span className={item.direction === 'lower-is-better' ? (item.delta <= 0 ? 'text-emerald' : 'text-crimson') : (item.delta >= 0 ? 'text-emerald' : 'text-crimson')}>{delta(item.delta, item.unit)}</span></div><p className="mt-2 text-[10px] text-ink/45">Current {item.current.toFixed(1)}{item.unit === '%' ? '%' : ` ${item.unit}`}</p></article>)}</div>
      {scenario && preview.metricDeltas.length > 7 && <section className="mt-5 rounded-xl border border-sky-200 bg-sky-50 p-5"><div className="flex items-center justify-between"><h4 className="font-bold text-sky-900">Scenario outcomes</h4><span className="text-[10px] uppercase tracking-widest text-sky-700">Engine preview</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{preview.metricDeltas.slice(7).map(item => <div key={item.key} className="rounded-lg bg-white p-3"><div className="flex justify-between gap-2 text-xs"><b>{item.label}</b><span className={item.delta >= 0 ? 'text-emerald' : 'text-crimson'}>{delta(item.delta, item.unit)}</span></div><p className="mt-2 text-xs text-ink/55">{item.current.toFixed(1)}{item.unit === '%' ? '%' : ` ${item.unit}`} → {item.alternative.toFixed(1)}{item.unit === '%' ? '%' : ` ${item.unit}`}</p></div>)}</div></section>}
      <div className="mt-5 grid gap-5 xl:grid-cols-3"><section className="rounded-xl border border-emerald/20 bg-emerald/8 p-5"><h4 className="font-bold text-emerald">What improves</h4>{preview.improves.length ? <ul className="mt-3 space-y-2 text-sm">{preview.improves.map(item => <li key={item.key} className="flex justify-between gap-3"><span>{item.label}</span><b className="text-emerald">{delta(item.delta, item.unit)}</b></li>)}</ul> : <p className="mt-3 text-sm text-ink/60">No measured outcome improves in this preview.</p>}</section><section className="rounded-xl border border-crimson/20 bg-crimson/8 p-5"><h4 className="font-bold text-crimson">What worsens</h4>{preview.worsens.length ? <ul className="mt-3 space-y-2 text-sm">{preview.worsens.map(item => <li key={item.key} className="flex justify-between gap-3"><span>{item.label}</span><b className="text-crimson">{delta(item.delta, item.unit)}</b></li>)}</ul> : <p className="mt-3 text-sm text-ink/60">No measured deterioration in this preview.</p>}</section><section className="rounded-xl border border-gold/25 bg-gold/10 p-5"><h4 className="font-bold text-gold">Trade-offs to notice</h4><ul className="mt-3 space-y-2 text-sm text-ink/70">{preview.tradeoffs.slice(0, 4).map(item => <li key={item}>• {item}</li>)}</ul></section></div>
      <div className="mt-5 rounded-xl border border-ink/10 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h4 className="font-bold">Learning interpretation</h4><p className="mt-2 max-w-3xl text-sm leading-6 text-ink/65">{preview.learningInsight}</p></div><div className="text-right text-xs text-ink/50"><p>Alternative spend</p><b className="text-lg text-ink">{formatCurrency(preview.alternative.spend.amount, currency)}</b><p>Current {formatCurrency(preview.current.spend, currency)}</p></div></div>{preview.uncovered.length > 0 && <p className="mt-4 rounded-lg bg-gold/10 p-3 text-xs text-ink/70"><b>Still uncovered:</b> {preview.uncovered.join(' · ')}</p>}{preview.warning && <p className="mt-4 rounded-lg bg-crimson/10 p-3 text-xs font-bold text-crimson">{preview.warning}</p>}<p className="mt-4 text-[10px] text-ink/45">This is a deterministic preview, not a recorded outcome. Applying it creates an editable next-quarter draft; the campaign advances only when you confirm the quarter.</p></div>
      <div className="mt-5 flex flex-wrap gap-2"><button onClick={() => setSaved(current => [...current, { name: name.trim() || 'Untitled strategy', selected, alloc, deployment, preview }])} className="flex items-center gap-2 rounded-lg border border-ink/15 bg-white px-4 py-3 text-sm font-bold"><Save size={15}/> Save draft</button><button disabled={!preview.valid || total !== 100} onClick={apply} className="flex items-center gap-2 rounded-lg bg-ink px-4 py-3 text-sm font-bold text-white disabled:opacity-35"><Zap size={15}/> Apply as next-quarter draft</button><button onClick={reset} className="flex items-center gap-2 rounded-lg border border-ink/15 px-4 py-3 text-sm font-bold"><RotateCcw size={15}/> Reset</button></div>{applied && <p className="mt-3 text-sm font-bold text-emerald">Draft applied. Review and edit the decision window before confirming.</p>}{saved.length > 0 && <div className="mt-5 border-t border-ink/10 pt-4"><p className="text-xs font-bold uppercase tracking-widest text-ink/45">Saved experiments</p><div className="mt-2 flex flex-wrap gap-2">{saved.map((item, index) => <button key={`${item.name}-${index}`} onClick={() => { setName(item.name); setSelected(item.selected); setAlloc(item.alloc); setDeployment(item.deployment); setApplied(false); }} className="rounded-lg bg-white px-3 py-2 text-xs font-bold">{item.name} · {item.preview.improves.length} gains</button>)}</div></div>}
    </section></div>
  </div></div>;
}
